### ISSUE TITLE
Using this plugin with a non-bootstrap theme?

### ISSUE THREAD

**Issue by macinchick** [kasperisager/vanilla-bootstrapmarkdown#2]
I'm using a theme I built on foundation for my vanilla forum. I've installed your plugin and mostly have it working, but it seems some javascript changes are needed. 

For example, the finished post displays correctly, but using the toolbar preview button results in unrendered markdown. Using the vanilla/non-plugin preview button shows correctly rendered text. (The InputFormatter is set to Markdown.)

Would you advise on making the javascript non-bootstrap dependent?

**Comment by kasperisager** [comment]
The plugin is simply a wrapper around the bootstrap-markdown plugin so you'd have to ask the maintainer of it regarding customisations.
