### ISSUE TITLE
Preview not working

### ISSUE THREAD

**Issue by tchncs** [kasperisager/vanilla-bootstrapmarkdown#3]
Hi, i am using your plugin with a bootstrap theme and just saw that posts previews wont work.
Regards and thanks for your nice plugin :)

Tested with Vanilla 2.2 and 2.1(?).

**Comment by kasperisager** [comment]
Previews are disabled on purpose as these are handled by Vanilla itself.

Reference: https://github.com/kasperisager/vanilla-bootstrapmarkdown/blob/master/js/src/main.js#L23-L25
